# Generated by Django 3.1.5 on 2022-04-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
