# Generated by Django 3.1.5 on 2022-02-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0005_auto_20220204_1826'),
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='stock_branch', to='Branch.branch', verbose_name='branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
