# Generated by Django 3.1.5 on 2022-03-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220313_0816'),
        ('Stock', '0003_auto_20220204_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_branch', to='Product.size', verbose_name='size'),
        ),
    ]
