# Generated by Django 3.1.5 on 2022-03-16 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20220315_1428'),
        ('Stock', '0004_stock_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='size',
        ),
        migrations.AddField(
            model_name='stock',
            name='size_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_size_instance', to='Product.size', verbose_name='size_instance'),
        ),
    ]
