# Generated by Django 3.1.5 on 2022-04-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_auto_20220316_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
    ]
