# Generated by Django 4.0.1 on 2022-01-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(verbose_name='size')),
                ('color', models.CharField(max_length=200, verbose_name='color')),
                ('image', models.ImageField(blank=True, default='image', null=True, upload_to='', verbose_name='image')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='price')),
                ('publish', models.BooleanField(default=False)),
                ('branches', models.ManyToManyField(blank=True, related_name='products_branches', to='Branch.Branch', verbose_name='branches')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Returned_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='unit_price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='total_price')),
                ('date_of_purchase', models.DateField(verbose_name='date_of_purchase')),
                ('date_of_return', models.DateTimeField(verbose_name='date_of_return')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_product_type', to='Product.product')),
            ],
            options={
                'verbose_name': 'Returned_Product',
                'verbose_name_plural': 'Returned_Products',
            },
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Product.category')),
            ],
            options={
                'verbose_name': 'Product_Type',
                'verbose_name_plural': 'Product_Types',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='Product.product_type'),
        ),
        migrations.CreateModel(
            name='Bad_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_product_branch', to='Branch.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_product_product_type', to='Product.product')),
            ],
            options={
                'verbose_name': 'Bad_Product',
                'verbose_name_plural': 'Bad_Products',
            },
        ),
    ]
