# Generated by Django 3.2.11 on 2022-02-03 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bad_product',
            options={'ordering': ['branch'], 'verbose_name': 'Bad_Product', 'verbose_name_plural': 'Bad_Products'},
        ),
        migrations.AddField(
            model_name='bad_product',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
