# Generated by Django 3.1.5 on 2022-03-15 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220313_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='bad_product',
            name='size_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bad_product_size_instance', to='Product.size', verbose_name='size_instance'),
        ),
        migrations.AddField(
            model_name='returned_product',
            name='size_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returned_product_size_instance', to='Product.size', verbose_name='size_instance'),
        ),
    ]
