# Generated by Django 3.1.5 on 2022-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20220315_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returned_product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total_price'),
        ),
        migrations.AlterField(
            model_name='returned_product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='unit_price'),
        ),
    ]
