# Generated by Django 3.1.5 on 2022-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_auto_20220406_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returned_product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='total_price'),
        ),
        migrations.AlterField(
            model_name='returned_product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='unit_price'),
        ),
    ]
