# Generated by Django 3.1.5 on 2022-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_auto_20220406_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='description', max_length=150, verbose_name='description'),
        ),
    ]
