# Generated by Django 3.1.5 on 2022-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='image', null=True, upload_to='', verbose_name='image'),
        ),
    ]
