# Generated by Django 4.0.1 on 2022-01-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Pre_Order', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_ordered_customer', to='User.customer', verbose_name='pre_ordered_customer'),
        ),
        migrations.AddField(
            model_name='pre_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_ordered_product', to='Product.product', verbose_name='pre_ordered_product'),
        ),
    ]
