# Generated by Django 3.1.5 on 2022-02-05 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Order', '0003_auto_20220204_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_order',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='archive'),
        ),
        migrations.AddField(
            model_name='pre_order',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
    ]
