# Generated by Django 3.1.5 on 2022-02-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Order', '0004_auto_20220205_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_order',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='qty'),
        ),
    ]
