# Generated by Django 3.1.5 on 2022-02-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Order', '0005_auto_20220206_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_order',
            name='qty',
            field=models.IntegerField(verbose_name='qty'),
        ),
    ]
