# Generated by Django 4.0.1 on 2022-01-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Branch', '0002_initial'),
        ('Sales', '0001_initial'),
        ('Credit_Sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='User.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='credit_sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sale_branch', to='Branch.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='credit_sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_sale_customer', to='User.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='credit_sale',
            name='items',
            field=models.ManyToManyField(related_name='credit_sale_Items', to='Sales.Items', verbose_name='items'),
        ),
    ]
