# Generated by Django 3.1.5 on 2022-02-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Sales', '0003_auto_20220204_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_sale',
            name='purchase_id',
            field=models.CharField(default='not set', max_length=150, verbose_name='purchase_id'),
            preserve_default=False,
        ),
    ]
