# Generated by Django 3.1.5 on 2022-02-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Sales', '0004_credit_sale_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_sale',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='credit_sale',
            name='fully_paid',
            field=models.BooleanField(default=False, verbose_name='fully_paid'),
        ),
        migrations.AddField(
            model_name='credit_sale',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total_payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_credit_sale', to='Credit_Sales.credit_sale', verbose_name='credit_sale'),
            preserve_default=False,
        ),
    ]
