# Generated by Django 3.1.5 on 2022-02-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Sales', '0005_auto_20220224_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
    ]
