# Generated by Django 3.1.5 on 2022-03-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit_Sales', '0006_remove_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_sale',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='expected_amount'),
            preserve_default=False,
        ),
    ]
