# Generated by Django 3.1.5 on 2022-02-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20220204_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='phone_number'),
        ),
    ]
