# Generated by Django 3.1.5 on 2022-03-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0006_auto_20220313_0816'),
        ('User', '0005_auto_20220218_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch', to='Branch.branch', verbose_name='branch'),
        ),
    ]
