# Generated by Django 4.0.1 on 2022-01-27 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Branch', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_product',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_branch', to='Branch.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='branch_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_product', to='Product.product', verbose_name='product'),
        ),
    ]
