# Generated by Django 3.2.11 on 2022-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_alter_branch_product_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_product',
            name='bad_qty',
            field=models.IntegerField(default=0, verbose_name='bad_qty'),
        ),
        migrations.AddField(
            model_name='branch_product',
            name='returned_qty',
            field=models.IntegerField(default=0, verbose_name='returned_qty'),
        ),
    ]
