# Generated by Django 3.1.5 on 2022-03-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220313_0816'),
        ('Branch', '0005_auto_20220204_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_product',
            name='is_multiple_sized',
            field=models.BooleanField(default=False, verbose_name='is_multiple_sized'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Branch Name'),
        ),
        migrations.CreateModel(
            name='Multiple_Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.IntegerField(default=0, verbose_name='current_qty')),
                ('returned_qty', models.IntegerField(default=0, verbose_name='returned_qty')),
                ('bad_qty', models.IntegerField(default=0, verbose_name='bad_qty')),
                ('branch_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch_product', verbose_name='multiple_size_branch_product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_product_sizes', to='Product.size')),
            ],
            options={
                'verbose_name': 'multiple_size',
                'verbose_name_plural': 'multiple_sizes',
            },
        ),
    ]
