# Generated by Django 3.1.5 on 2022-03-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0007_auto_20220318_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_size',
            name='branch_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch_product', verbose_name='multiple_size_branch_product'),
        ),
    ]
