# Generated by Django 4.0.1 on 2022-01-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='qty')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit_price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total_price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_product', to='Product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Items',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total_amount')),
                ('remark', models.CharField(max_length=200, verbose_name='remark')),
                ('channel', models.CharField(choices=[('web', 'web'), ('store', 'store')], max_length=5, verbose_name='channel')),
                ('payment_method', models.CharField(choices=[('transfer', 'transfer'), ('cash', 'cash'), ('online', 'online')], max_length=8, verbose_name='payment_method')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='customer_name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone_number')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=254, verbose_name='address')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_branch', to='Branch.branch', verbose_name='branch')),
                ('items', models.ManyToManyField(related_name='items', to='Sales.Items', verbose_name='items')),
            ],
            options={
                'verbose_name': 'Sales',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
