# Generated by Django 3.1.5 on 2022-02-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20220215_2339'),
        ('Sales', '0002_auto_20220204_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='multipleSIzes',
            field=models.ManyToManyField(blank=True, related_name='items_multiplesizes', to='Product.Size', verbose_name='multiplesizes'),
        ),
        migrations.AddField(
            model_name='sales',
            name='purchase_id',
            field=models.CharField(default='not set', max_length=150, verbose_name='purchase_id'),
            preserve_default=False,
        ),
    ]
