# Generated by Django 3.1.5 on 2022-02-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_auto_20220215_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='multipleSIzes',
        ),
        migrations.AddField(
            model_name='items',
            name='color',
            field=models.CharField(default='not set', max_length=200, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='product_type',
            field=models.CharField(default='not set', max_length=200, verbose_name='size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.CharField(default='not set', max_length=200, verbose_name='product_type'),
            preserve_default=False,
        ),
    ]
