# Generated by Django 3.1.5 on 2022-02-18 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20220218_1704'),
        ('Sales', '0004_auto_20220216_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_customer', to='User.customer', verbose_name='customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'transfer'), ('cash', 'cash'), ('credit', 'credit'), ('online', 'online')], max_length=8, verbose_name='payment_method'),
        ),
    ]
