# Generated by Django 3.1.5 on 2022-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_auto_20220218_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='expected_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='expected_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='mini_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='mini_price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='expected_amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='product_type',
            field=models.CharField(max_length=200, verbose_name='product_type'),
        ),
        migrations.AlterField(
            model_name='items',
            name='size',
            field=models.CharField(max_length=200, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'transfer'), ('cash', 'cash'), ('credit', 'credit')], max_length=8, verbose_name='payment_method'),
        ),
    ]
