# Generated by Django 3.1.5 on 2022-03-15 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20220313_0816'),
        ('Sales', '0006_auto_20220224_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='size_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_size_instance', to='Product.size', verbose_name='size_instance'),
        ),
    ]
