# Generated by Django 3.1.5 on 2022-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_items_size_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='fully_paid'),
        ),
    ]
