# Generated by Django 3.1.5 on 2022-04-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_sales_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='paid'),
        ),
    ]
