# Generated by Django 3.1.5 on 2022-05-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_auto_20220428_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-date'], 'verbose_name': 'Sales', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='destination',
            field=models.CharField(blank=True, default='not set', max_length=256, verbose_name='destination'),
        ),
    ]
